name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@master
        with:
          github_user_name: BODYsuperman  
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate github-contribution-grid-snake.svg
          file_pattern: dist/github-contribution-grid-snake.svg
